CREATE TABLE "GCG_6275_CUSTRFQ" (
 "RFQ" CHAR(7) NOT NULL,
 "LINE_RFQ" CHAR(3) NOT NULL,
 "NOTES" LONGVARCHAR,
 "SALESPERSON" VARCHAR(30),
 "BUYER" VARCHAR(30),
 "RFQ_DUE_DATE" VARCHAR(25),
 "ENGINEER" VARCHAR(30),
 "STATUS" VARCHAR(30),
 "RFQ_DATE" VARCHAR(10),
 "RFQ_TIME" VARCHAR(50),
 "ESTIMATOR" CHAR(8),
 "PRIORITY" CHAR(6),
 "DIFFICULTY" CHAR(6),
 "SCHEDULING" CHAR(6),
 "MAT_PROC" CHAR(6),
 "PROJECT_NO" CHAR(15),
 "Scenario" CHAR(2),
 "Range" CHAR(10),
 "NoBid" CHAR(10),
 "PartNumber" CHAR(20),
 "PartDesc" CHAR(30),
 "TargetQty" INTEGER,
 "UOM" CHAR(2),
 "LeadTimeDays" INTEGER,
 "RatePerMonth" DOUBLE,
 "OriginCountry" CHAR(20),
 "ExportClass" CHAR(20),
 "PriceType" CHAR(20),
 "CommercialPart" CHAR(20),
 "ByYear" CHAR(4),
 "YearsQuoting" CHAR(20),
 "PeriodofPerf" CHAR(10),
 "Year1Qty" INTEGER,
 "Year1Bid" DOUBLE,
 "Year2Qty" INTEGER,
 "Year2Bid" DOUBLE,
 "Year3Qty" INTEGER,
 "Year3Bid" DOUBLE,
 "Year4Qty" INTEGER,
 "Year4Bid" DOUBLE,
 "Year5Qty" INTEGER,
 "Year5Bid" DOUBLE,
 "Year6Qty" INTEGER,
 "Year6Bid" DOUBLE,
 "Year7Qty" INTEGER,
 "Year7Bid" DOUBLE,
 "Year8Qty" INTEGER,
 "Year8Bid" DOUBLE,
 "Year9Qty" INTEGER,
 "Year9Bid" DOUBLE,
 "Year10Qty" INTEGER,
 "Year10Bid" DOUBLE,
 "NRECharges" CHAR(20),
 "SpecialCharges" DOUBLE,
 "ToolingCharges" DOUBLE);

CREATE INDEX "GCG_6275_CUSTRFQ" ON "GCG_6275_CUSTRFQ"("RFQ", "LINE_RFQ");